name: Build Windows Manually

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'  # 可以根据需要调整版本

      - name: Build for Windows
        run: |
          go build -o qrcp.exe
        shell: bash  # 使用 bash shell 以便更灵活地执行命令

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: qrcp-windows
          path: qrcp.exe
